config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # verb '/path', to: 'controller#action'
  # get "/search", to: "songs#search"
  get "/songs/named/:name", to: "songs#search"
  resources :songs do
    resource :reviews, only: [:new, :create]
  end
  # # CRUD
  # # CREATE - 1 see the form 2 submit the form
  # get '/songs/new', to: 'songs#new' #=> TO DISPLAY THE FORM
  # post '/songs', to: 'songs#create'

  # # READ - 1 read all or 2 read one
  # get '/songs', to: 'songs#index'
  # get '/songs/:id', to: 'songs#show' #=> /songs/12345

  # # UPDATE - 1 see the form 2 submit the form
  # get '/songs/:id/edit', to: 'songs#edit' #=> TO DISPLAY THE FORM
  # patch '/songs/:id', to: 'songs#update'

  # # DELETE
  # delete '/songs/:id', to: 'songs#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :song
  validates :content, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @song = Song.find(params[:song_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @song = Song.find(params[:song_id])
    @review.song = @song #=> MUST BE AN INSTANCE OF SONG!
    # raise
    if @review.save
      redirect_to song_path(@song)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  # READ ALL
  def index
    @songs = Song.all
  end

  # READ ONE
  def show
    @song = Song.find(params[:id])
  end

  def new
    # use this action to render the form!
    @song = Song.new
  end

  def create
    raise
    @song = Song.new(song_params)
    if @song.save
      redirect_to song_path(@song)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def search
    # raise
    # params => {"query"=>"thriller"}
    # @songs = Song.where(title: params[:query])
    # SELECT * FROM songs WHERE title = ??????
    # raise

    @songs = Song.where(title: params[:name])
  end

  private

  def song_params
    params.require(:song).permit(:title, :category, :year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsQuiz1176</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<h1>Add a review</h1>
<%#  /songs/:song_id/reviews %>
<%= form_with model: [@song, @review] do |f| %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1>All songs</h1>

<% @songs.each do |song| %>
  <p><%= song.title %> | <%= song.year %> | <%= song.category %></p>
<% end %>

app/views/songs/new.html.erb
<%= form_with model: @song do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :category %>
  <%= f.number_field :year %>
  <%= f.submit %>
<% end %>

app/views/songs/search.html.erb
<h1>Songs</h1>

<% @songs.each do |song| %>
  <p><%= song.title %> | <%= song.year %></p>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<p><%= @song.year %></p>
<p><%= @song.category %></p>

<h2>Here are the reviews for this song:</h2>
<% @song.reviews.each do |review| %>
  <p><%= review.content %></p>
<% end %>

<%= link_to "Add review", new_song_reviews_path(@song) %>